### ISSUE TITLE
Make Timecode editable in readable format

### ISSUE THREAD

**Issue by feedhopper** [Ellpeck/ObsidianSimpleTimeTracker#9]
Sometimes I forget to switch the timer off. I then usually have a rough idea of how much time I spent on this particular chunk of work. So I then edit the codeblock to something close to this.

The problem I have: The code looks like this:
"startTime":1666021639,"endTime":1666027580}

This makes it very hard to adjust the time, It would be fantastic if the time parameters could be made editable like the segment name. Switching fields could easily be done by using the tab key.

**Comment by guategeek** [comment]
I just found this plugin, trying to find something to replace [pendulums](https://pendulums.io) as it keeps freezing on me and figured something right in Obsidian would be the best. I want to be able to manually add in my own times for past tasks, or like the original poster here edit the times. But the timestamps make no sense to me, so I would also love if they could be editable, or if the underlying format was more human readable.

**Comment by iatharva** [comment]
Hello all, I was also facing a similar situation as @feedhopper, so I was also looking for a way to edit the added timestamp.
I believe @Ellpeck has closed the PR and this Issue (Enhancement) as well, so would this feature not be implemented or will it take time since you are planning to add some more enhancement with that feature?

Other than that, Thanks for the plugins, I use it on a daily purpose apart from this I don't have any other feedback.

**Comment by Ellpeck** [comment]
This issue has not been closed, it's still planned!
